CREATE TABLE PACIENTE(re_pac INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
					nome_pac VARCHAR(50) NOT NULL,
					sexo_pac VARCHAR(10),
					dataNasc_pac DATE);
					
CREATE  TABLE MEDICO (
CRM_med INT NOT NULL PRIMARY KEY,
Nome_med VARCHAR(45) NOT NULL ,
Especialidade  VARCHAR(45) NOT NULL ,
Usuario_idUsuario INT NOT NULL);

	CREATE TABLE CONSULTA(
	ID_CONSULTA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CRM_MEDIC INT NOT NULL,
	RE_PACIENT INT NOT NULL,
	DATA_CONSULTA DATE NOT NULL,
	HORARIO_CONSULTA VARCHAR(10) NOT NULL );
	
	CREATE TABLE HISTORICO(
	ID_HISTORICO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CRM_MEDIC INT NOT NULL,
	RE_PACIENT INT NOT NULL,
	DATA_CONSULTA DATE NOT NULL,
	HORARIO_CONSULTA VARCHAR(10) NOT NULL );
	
	CREATE TABLE ANAMNESE(
	ID_ANAMNESE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	ID_HIS INT NOT NULL,
	RE_PACIENT INT NOT NULL,
	DATA_CONSULTA DATE NOT NULL,
	HORARIO_CONSULTA VARCHAR(10) NOT NULL );
	
	CREATE TABLE EXAMES(
	ID_EXAME INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOME_EXAME VARCHAR(50)NOT NULL,
	ID_PACI INT NOT NULL,
	RESULTADO INT NOT NULL,
	ANO INT NOT NULL

);
